name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"
  workflow_call:
    inputs:
      secrets-context:
        description: 'JSON-formatted object'
        type: string
      your-secret: 
        description: 'PAT with repo scope'
        type: string

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade use-secrets activity
        id: check-secrets
        uses: ./.github/actions/check-secrets-action
        with:
          secrets-context: ${{ toJSON(secrets) }}
          your-secret: ${{ secrets.Secret_Token }}
